# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Prefere aspas simples para strings, promovendo consistência.
    - prefer_single_quotes

    # Garante que todos os construtores de widgets tenham uma chave (key), importante para otimização e testes.
    - use_key_in_widget_constructors

    # Incentiva o uso de construtores `const` quando possível, o que melhora a performance do Flutter.
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations

    # Ajuda a evitar widgets `Container` desnecessários que não adicionam valor visual ou de layout.
    - avoid_unnecessary_containers

    # Garante que os tipos de retorno das funções sejam sempre declarados explicitamente, melhorando a legibilidade e segurança de tipo.
    - always_declare_return_types

    # Incentiva a declaração explícita de tipos para variáveis locais, melhorando a legibilidade.
    - always_specify_local_types

    # Garante que os métodos de override sejam marcados com @override.
    - annotate_overrides

    # Evita a declaração de variáveis que não são usadas.
    - unused_local_variable
    - unused_field

    # Promove a consistência na nomenclatura de arquivos.
    - file_names

    # Ajuda a manter a consistência na nomenclatura de classes.
    - camel_case_types

    # Ajuda a manter a consistência na nomenclatura de variáveis e funções.
    - camel_case_function_names

    # Garante que os parâmetros nomeados sejam sempre obrigatórios, a menos que explicitamente marcados como opcionais.
    - require_trailing_commas

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
